# Generated by Django 3.0.4 on 2020-04-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('pic', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('press', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('introduction', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'ordering': ['c_time'],
            },
        ),
    ]
