# Generated by Django 3.0.4 on 2020-04-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collection',
            field=models.CharField(default='[]', max_length=256),
            preserve_default=False,
        ),
    ]
